


###
POST http://127.0.0.1:5000/task-manager
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "projectTitle": "to you, from me",
    "index": 0,
    "statusMark": 0
}

###


PUT http://127.0.0.1:5000/completed-project-manager
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "projectTitle": "to you, from me again"
}



###