


###
POST http://127.0.0.1:5000/task-manager
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "projectTitle": "to you, from me",
    "index": 0,
    "statusMark": 0
}

###


PUT http://127.0.0.1:5000/completed-project-manager
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "projectTitle": "to you, from me again"
}



###


PUT http://127.0.0.1:5000/title-update
Content-Type: application/json

{
    "user": "calhounbryce13@gmail.com",
    "category": "current",
    "old-title": "website aethetics",
    "new-title": "website aesthetics"
}
###

PUT http://127.0.0.1:5000/goal-update 
Content-Type: application/json

{
    "user": "calhounbryce13@gmail.com",
    "category": "current",
    "title": "Projectory alt colors",
    "new-goal": "Change the yellow buttons to a cool dark alternative"
}